### ISSUE TITLE
LACNIC TAL is outdated

### ISSUE THREAD

**Issue by salfers** [cloudflare/cfrpki#109]
With the current default configuration of OctoRPKI it does not sucessfully fetch anything for LACNIC.

The current [shipped file](https://github.com/cloudflare/cfrpki/blob/master/cmd/octorpki/tals/lacnic.tal) is different from the one on the LACNIC website: https://www.lacnic.net/4984/2/lacnic/rpki-rpki-trust-anchor

**Comment by taktv6** [comment]
Fixed in https://github.com/cloudflare/cfrpki/pull/110
