### ISSUE TITLE
OctoRPKI service status FAILURE

### ISSUE THREAD

**Issue by rencarlo014** [cloudflare/cfrpki#143]
Unable to start OctoRPKI service due to the below error:

root@octorpki:/home/octorpki# systemctl status octorpki
× octorpki.service - OctoRPKI
     Loaded: loaded (/lib/systemd/system/octorpki.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-04-29 08:36:33 UTC; 1s ago
    Process: 1891 ExecStart=/usr/bin/octorpki $OCTORPKI_ARGS (code=exited, status=1/FAILURE)
   Main PID: 1891 (code=exited, status=1/FAILURE)
        CPU: 15ms

Apr 29 08:36:33 octorpki systemd[1]: Started OctoRPKI.
Apr 29 08:36:33 octorpki octorpki[1891]: time="2023-04-29T08:36:33Z" level=info msg="Validator started"
Apr 29 08:36:33 octorpki octorpki[1891]: time="2023-04-29T08:36:33Z" level=fatal msg="Failed to create directories \"cache/\": mkdir cache/: permission denied"
Apr 29 08:36:33 octorpki systemd[1]: octorpki.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 08:36:33 octorpki systemd[1]: octorpki.service: Failed with result 'exit-code'.

any recommendations to fix this? thank you.

**Comment by taktv6** [comment]
Hi, I guess you installed the debian package?

Please check if this change https://github.com/cloudflare/cfrpki/pull/144/files applied to `/lib/systemd/system/octorpki.service` fixes your issue.

Thanks
takt

**Comment by rencarlo014** [comment]
> Hi, I guess you installed the debian package?
> 
> Please check if this change https://github.com/cloudflare/cfrpki/pull/144/files applied to `/lib/systemd/system/octorpki.service` fixes your issue.
> 
> Thanks takt

octorpki@octorpki:~$ sudo systemctl status octorpki.service        
× octorpki.service - OctoRPKI
     Loaded: loaded (/lib/systemd/system/octorpki.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-04-29 09:37:40 UTC; 3s ago
    Process: 3263 ExecStart=/usr/bin/octorpki -cache=/var/lib/octorpki/cache -output.sign=false (code=exited, status=1/FAILURE)
   Main PID: 3263 (code=exited, status=1/FAILURE)
        CPU: 8ms

Apr 29 09:37:40 octorpki systemd[1]: Started OctoRPKI.
Apr 29 09:37:40 octorpki octorpki[3263]: time="2023-04-29T09:37:40Z" level=info msg="Validator started"
Apr 29 09:37:40 octorpki octorpki[3263]: time="2023-04-29T09:37:40Z" level=fatal msg="Failed to create directories \"/var/lib/octorpki/cache\": mkdir /var/lib/octorpki: permission denie>
Apr 29 09:37:40 octorpki systemd[1]: octorpki.service: Main process exited, code=exited, status=1/FAILURE
Apr 29 09:37:40 octorpki systemd[1]: octorpki.service: Failed with result 'exit-code'.

same issue after the change.

**Comment by taktv6** [comment]
Please provide the output of the following command:
`ls -l /var/lib`

**Comment by rencarlo014** [comment]
> Please provide the output of the following command: `ls -l /var/lib`

octorpki@octorpki:~$ ls -l /var/lib
total 152
drwxr-xr-x  3 root      root      4096 Feb 17 17:23 apport
drwxr-xr-x  5 root      root      4096 Apr 29 08:25 apt
drwxr-xr-x  2 root      root      4096 Feb  7  2022 boltd
drwxr-xr-x  8 root      root      4096 Apr 29 08:22 cloud
drwxr-xr-x  2 root      root      4096 Apr 29 06:25 command-not-found
drwxr-xr-x  2 root      root      4096 Apr 29 06:42 dbus
drwxr-xr-x  2 root      root      4096 Oct  4  2022 dhcp
drwxr-xr-x  7 root      root      4096 Apr 29 08:25 dpkg
drwxr-xr-x  2 root      root      4096 Feb  8 13:57 git
drwxr-xr-x  4 root      root      4096 Apr 29 06:39 grub
drwxr-xr-x  2 landscape landscape 4096 Apr 29 06:51 landscape
drwxr-xr-x  2 root      root      4096 May 25  2022 logrotate
drwxr-xr-x  2 root      root      4096 Feb 17 17:24 man-db
drwxr-xr-x  2 root      root      4096 Apr 18  2022 misc
drwxr-xr-x  2 root      root      4096 Mar 24  2022 os-prober
drwxr-xr-x  2 root      root      4096 Apr 29 07:42 PackageKit
drwxr-xr-x  2 root      root      4096 Apr 29 08:20 pam
drwxr-xr-x  2 root      root      4096 Mar 18  2022 plymouth
drwx------  3 root      root      4096 Feb 17 17:23 polkit-1
drwx------  2 root      root      4096 Feb 17 17:23 private
drwxr-xr-x  2 root      root      4096 Feb 17 17:23 python
-rw-r--r--  1 root      root         0 Feb 17 17:20 shells.state
drwxr-xr-x 22 root      root      4096 Apr 29 13:45 snapd
drwxr-xr-x  3 root      root      4096 Feb 17 17:23 sudo
drwxr-xr-x 11 root      root      4096 Apr 29 06:46 systemd
drwxr-xr-x  2 tss       tss       4096 Jan 25  2022 tpm
drwxr-xr-x  4 root      root      4096 Apr 29 15:14 ubuntu-advantage
drwxr-xr-x  2 root      root      4096 Mar 16  2022 ubuntu-drivers-common
drwxr-xr-x  2 root      root      4096 Apr 29 06:51 ubuntu-release-upgrader
drwxr-xr-x  3 root      root      4096 Apr 29 06:40 ucf
drwx------  2 root      root      4096 Apr 29 06:46 udisks2
drwxr-xr-x  2 root      root      4096 Jan 14  2022 unattended-upgrades
drwxr-xr-x  2 root      root      4096 Apr 29 06:51 update-manager
drwxr-xr-x  4 root      root      4096 Apr 29 08:25 update-notifier
drwxr-xr-x  2 root      root      4096 Mar  9  2022 upower
drwxr-xr-x  2 root      root      4096 Mar 25  2022 usb_modeswitch
drwxr-xr-x  2 root      root      4096 Feb 17 17:24 usbutils
drwxr-xr-x  3 root      root      4096 Feb 17 17:24 vim
drwxr-xr-x  3 root      root      4096 Apr 29 06:46 vmware

sorry for the late response, here's the output.

**Comment by rencarlo014** [comment]
Hello, @taktv6. I've already resolved the problem by changing the permission on /usr/bin/octorpki. Thanks for your help.
