### ISSUE TITLE
octorpki seems to choke on certs with multiple prefixes

### ISSUE THREAD

**Issue by dotwaffle** [cloudflare/cfrpki#26]
When trying to run octorpki, it looks like it is choking on this file:

[wu2-b8OX-KCC5qOjm3zOTSWbziE.cer.gz](https://github.com/cloudflare/cfrpki/files/3497942/wu2-b8OX-KCC5qOjm3zOTSWbziE.cer.gz)

```
ERRO[0002] Error adding Resource wu2-b8OX-KCC5qOjm3zOTSWbziE.cer: c2edbe6fc397f8a082e6a3a39b7cce4d259bce21 contains invalid IP addresses: [Min: 45.253.244.0 max: 45.253.255.255 61.29.240.0/20]
```

openssl shows:

```
% openssl x509 -inform DER -text -in ./cache/rpki.cnnic.cn/rpki/A9162E3D0000/wu2-b8OX-KCC5qOjm3zOTSWbziE.cer -noout
            sbgp-ipAddrBlock: critical
                IPv4:
                  45.253.244.0-45.253.255.255
                  61.29.240.0/20
                  103.64.24.0-103.64.127.255
                  103.64.140.0-103.64.147.255
```

**Comment by lspgn** [comment]
Hi @dotwaffle,
Thank you for pointing the issue.
The IPs are not contained in the parent certificate anymore (id: 041629b6a9eab7cb1324ea3978f03796f889b540).
It happened to LACNIC in the past.

There was a certificate rollover around 2019-08-13 01:20:00.
The following is the diff of the two certificates.

```
###
<         "45.253.243.255"
---
>         "45.254.31.255"
###
<       "prefix": "45.254.0.0/19"
###
<       "ip-range": [
<         "61.29.128.0",
<         "61.29.239.255"
<       ]
---
>       "prefix": "61.29.128.0/17"
###
<   "validfrom": 1565658527,
---
>   "validfrom": 1565237314,
###
<   "serial": "45928"
---
>   "serial": "45830"
```

The certificate c2edbe6fc397f8a082e6a3a39b7cce4d259bce21 should have been removed as 2019-08-15 12:50:00.

Let me know if you have more questions,
Best,
Louis
