### ISSUE TITLE
don't run rsync or rrdp - "validate only mode"

### ISSUE THREAD

**Issue by job** [cloudflare/cfrpki#31]
Is there a way to run octorpki like we can run `rpki-client -n` or `routinator vrps -n`?

In both tools the `-n` flag means to only do the validation step, and assume that the `-cache /var/cache/rpki-client` directory is fully populated

**Comment by lspgn** [comment]
Just following up from a private chat:
I never thought of adding this option inside OctoRPKI, nonetheless, [localrpki](https://github.com/cloudflare/cfrpki/blob/master/cmd/localrpki/localrpki.go) should solve this issue.

```
go get github.com/cloudflare/cfrpki/cmd/localrpki
```

should produce `~/go/bin/localrpki` binary
