### ISSUE TITLE
Add sbgp-ipAddrBlock prefixes to slurm-style 'prefixfilter' when CA PP distrusted

### ISSUE THREAD

**Issue by job** [cloudflare/cfrpki#40]
Add `sbgp-ipAddrBlock` prefixes to slurm-style 'prefixfilter' when CA PP distrusted, so that missing ROAs in one part of the tree does not negatively affect BGP when the ROAs from the other side of the tree are used.

Similar thinking is done here https://github.com/NLnetLabs/routinator/issues/319#issuecomment-620681783

Draft forthcoming.

**Comment by lspgn** [comment]
This is a good idea.
Will add it as a configurable flag at the moment.
