### ISSUE TITLE
Error adding Resource tals/arin.tal: illegal base64 data

### ISSUE THREAD

**Issue by nskalis** [cloudflare/cfrpki#53]
Hi,

Would you be so kind to advise how to resolve the error with the ARIN TAL

```
Jul 08 09:06:47 xxx octorpki[23556]: time="2020-07-08T09:06:47+02:00" level=error msg="Error adding Resource tals/arin.tal: illegal base64 data at input byte 4"
```

I am attaching here the `arin.tal` with the `.txt` file extension (for GitHub to allow the upload)
[arin.tal.txt](https://github.com/cloudflare/cfrpki/files/4889052/arin.tal.txt)

**Comment by lspgn** [comment]
Hi @nskalis,
This is fixed in the next release. I added support for TAL with an HTTPs address.
In the meantime, you can compile the latest OctoRPKI or remove the line with https in the TAL to use with a previous version.

**Comment by nskalis** [comment]
thanks!

- do you know maybe when the next release is expected?
- `remove the line with https in the TAL to use with a previous version` do you mean instead of `https://rrdp.arin.net/arin-rpki-ta.cer` to use `http://rrdp.arin.net/arin-rpki-ta.cer`?
- do you mind keeping this issue open till the next release becomes available?

**Comment by lspgn** [comment]
I'll try to do it this week.
Remove the entire line, so that only the Rsync URL and the base64 remain.

**Comment by lspgn** [comment]
Added https tal as part of the previous pre-release.
v1.2.0 was released today. Feel free to reopen if the issue persists.
