### ISSUE TITLE
TA's tree should've been considered invalid because of invalid signature identifier 

### ISSUE THREAD

**Issue by job** [cloudflare/cfrpki#66]
Yesterday ARIN introduced incorrect algorithm identifier encodings in their RPKI data.

It appears that for some reason Cloudflare's RPKI validation process did not catch this error and continued to produce VRPs based on cryptographically invalid data

A more detailed analysis of what transpired is available here http://sobornost.net/~job/arin-manifest-issue-2020.08.12.txt

ARIN confirmed the analysis was correct and is now working to restore CA services.

tested on cfrpki 1.2.0-pre

**Comment by job** [comment]
A dump of the broken data is available here http://sobornost.net/~job/arin-broken-state-20200812.tar.gz

the RIR is expected to fix the issue in the next few hours

**Comment by lspgn** [comment]
Thanks for raising! I'll try to come up with a fix by next week.

**Comment by mahtin** [comment]
Cross referencing over to https://github.com/NLnetLabs/routinator/issues/365#issuecomment-673569038
