### ISSUE TITLE
.deb package overwriting /etc/default/octorpki

### ISSUE THREAD

**Issue by jtkristoff** [cloudflare/cfrpki#75]
Upgraded a pre 1.2.0 OctoRPKI with the current 1.2.0 .deb package.  Worked fine with one minor hitch.  Perhaps ask or warn about updating an existing /etc/default/octorpki since when it overwrote mine it took a bit of debugging to realize my gortr rpki-rtr was no longer serving any data.  Having signed the output by default, this was removed with this package install.

**Comment by lspgn** [comment]
I will have a look. I am not too familiar with FPM but I will look into the options available ([this maybe](https://github.com/jordansissel/fpm/issues/937)). Thank you for the report!

**Comment by laxxie** [comment]
Yeah, it would be great to get a warning. I use "-http.addr=" which was overwritten and i was wondering why the server didn't serve any data to the router

**Comment by lspgn** [comment]
My apologies for the issue :( .
I found out it was due to `--deb-no-default-config-files` flag.
Prepared a PR on this repo (and GoRTR which had the same issue)
FPM indicates:
```
Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag {:level=>:warn}
```
