### ISSUE TITLE
Logging message on HTTP server start

### ISSUE THREAD

**Issue by dotwaffle** [cloudflare/cfrpki#8]
I'm not sure how to best solve this, but by default you're using `/output.json` as `output.roa` which works for a Docker container in oneoff mode, and it works in server mode, but it doesn't work on most systems as it's going to try to write to disk at `/`.

I think it's probably best to change:
* https://github.com/cloudflare/cfrpki/blob/master/cmd/octorpki/octorpki.go#L755 to `log.Infof("Serving HTTP on %v/%v", addr, path)`, and prepending a `/` to the Handlers if not already present (otherwise the server will return a 404).
* https://github.com/cloudflare/cfrpki/blob/master/cmd/octorpki/octorpki.go#L75 to `Output   = flag.String("output.roa", "output.json", "Output ROA file or URL")`

That should mean that users will be able to run "oneoff" or "server" modes with the defaults without having to try different things via a process of trial and error.

Thoughts?

**Comment by lspgn** [comment]
This makes sense.
Will remove the `/` from defaults and will add it to the http handler.
