### ISSUE TITLE
Question on data inconsistency between OctoRPKI and other validators

### ISSUE THREAD

**Issue by xleonzhao** [cloudflare/cfrpki#81]
Hi, I am trying to understand why some ROAs appearing in OctoRPKI dataset but not in other validators. For example, <103.10.0.0/24, 24, 59083> is [valid](https://rpki.cloudflare.com/?view=validator&validateRoute=59083_103.10.0.0%2F24&ta=apnic&asn=59083&prefix=103.10.0.0%2F24&prefixMatch=lspec&extendedMode=true&explorerTab=list) by OctoRPKI but neither RIPENCC validator nor Routinator has no this very ROA. 

Here is the response from routinator:
```
{
  "validated_route": {
    "route": {
      "origin_asn": "AS59083",
      "prefix": "103.10.0.0/24"
    },
    "validity": {
      "state": "not-found",
      "description": "No VRP Covers the Route Prefix",
      "VRPs": {
        "matched": [
        ],
        "unmatched_as": [
        ],
        "unmatched_length": [
        ]      }
    }
  }
}
```

Any idea why? Thanks!

**Comment by lspgn** [comment]
Hi @xleonzhao 
I won't be able to speak for the other validators on why the ROA is absent from the output.
Are you validating the same dataset? cnnic often has fetching issues.
Is the file `rsync://rpki.cnnic.cn/rpki/A9162E3D0000/577/WwWuRd1wZIBACoGFEB7fcPuyYPQ.roa` present for all three?
Are the other validators rejecting it or do not have it?
There is a delay on the RPKI dashboard as well.

Could you check with [RTRmon](https://github.com/cloudflare/gortr/blob/master/cmd/rtrmon/rtrmon.go) the differences between the output?

Additionally, I'm seeing the file is present on [rpki-client](http://console.rpki-client.org/rpki.cnnic.cn/rpki/A9162E3D0000/577/WwWuRd1wZIBACoGFEB7fcPuyYPQ.roa.html).

Thank you

**Comment by lukastribus** [comment]
For Routinator you need to use version 0.8.2.
For RPKI NCC validator, you can't currently use it.

**Comment by xleonzhao** [comment]
Thanks @lspgn for your response. 

> Are you validating the same dataset? cnnic often has fetching issues.

Yes, we are actually running 3 RPKI validators side-by-side to fetch data from usual 5 TALs

> Is the file rsync://rpki.cnnic.cn/rpki/A9162E3D0000/577/WwWuRd1wZIBACoGFEB7fcPuyYPQ.roa present for all three?

Routinator saw the file, but v0.8.0 failed the validation, v0.8.2 (released yesterday?) passed it.
RIPE validator has no such file.

> Which versions are you using?

Routinator v0.8.0 -> v0.8.2
OctoRPKI v1.1.4 (2019-08-06T16:51:07-0700)
Ripencc validator v3.2-2020.10.28.23.06

**Comment by xleonzhao** [comment]
@lukastribus Thanks for the insight. Routinator 0.8.2 does seem working better.

> For RPKI NCC validator, you can't currently use it.

why? can you please elaborate on it a bit?

**Comment by lukastribus** [comment]
Sorry I did not have time to elaborate yesterday. The bugs you are seeing are based on a misunderstanding of an upcoming RFC.

You can read more about it in the routinator 0.8.2 release notes:
https://www.nlnetlabs.nl/news/2020/Dec/09/routinator-0.8.2-released/

RIPE RPKI validator is not yet fixed.

**Comment by lukastribus** [comment]
Afaik octorpki also has the same issue in v1.2.0 and v1.2.1, while v1.2.2 should be fine. But since you are using v1.1.4, you did not see it there.

**Comment by lukastribus** [comment]
rpki-validator-3 3.2-2020.12.10 was just released with the fix for this.

**Comment by xleonzhao** [comment]
Thanks again @lukastribus. Time to upgrade.

**Comment by lspgn** [comment]
@xleonzhao will close. Feel free to re-open if the issue reappears.
